### ISSUE TITLE
Consider merging with Lightship

### ISSUE THREAD

**Issue by gajus** [nodeshift/kube-probe#75]
Hello, I have came across this project by accident and it duplicates what I have already solved with Lightship.

https://github.com/gajus/lightship

Perhaps there is interest to deprecate kube-probe in favor of Lightship (or vice-versa) and join forces?

I must say I do prefer the Lightship implementation for the simple reason that it creates a separate, non-public HTTP server for liveness checks. It also provides a concept of [beacon](https://github.com/gajus/lightship#beacons), which I found particularly useful for processes that run long tasks that cannot be interrupted.

**Comment by lholmquist** [comment]
Hi,  Thanks for stopping by :)  Lightship looks like an interesting project, but at the moment, i don't think there is any interest in deprecating this module.
