### ISSUE TITLE
Shut off Overload Protection if needed

### ISSUE THREAD

**Issue by lholmquist** [nodeshift/kube-probe#89]
From an outside user:

> In regards to overload protection:

> For situations where a service has a vertical ceiling and cannot grow horizontally, overload-protection makes sense.

> If the service can grow horizontally, I do not think overload protection is needed as replicas can be spun up and account for more traffic (wheras overload-protection would return 503s until it is ready to respond)."

We can probably pass a flag to turn off each probes overload protection

**Comment by deewhyweb** [comment]
I've just pushed a PR related to this issue:
https://github.com/nodeshift/kube-probe/pull/91

**Comment by lholmquist** [comment]
@deewhyweb I see you closed the PR,  did you get your issue sorted out without having to do this?

**Comment by deewhyweb** [comment]
I removed it, going to submit a different version

**Comment by aalykiot** [comment]
@lholmquist I can take a look at kube-probe's code (cause I'm unfamiliar with what it does) and see if I can do anything about this overload-protection thing

**Comment by lholmquist** [comment]
@alexalikiotis sounds good.   it should be pretty simple&trade;
